Dasharo/meta-dts

- meta-dts-distro/recipes-dts/reports/dasharo-hcl-report/dasharo-hcl-report
If there are multiple default gateways, the command would list two interfaces, and consequently won't find the sysfs file with the MAC address.
Fix this by taking the first one. And also quote the variable.
Signed-off-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
> dasharo-hcl-report: fix handling multiple default route

- meta-dts-distro/recipes-dts/packagegroups/packagegroup-dts.bb
- meta-dts-distro/recipes-support/ipxe-commands/files/ipxe-commands.service
- meta-dts-distro/recipes-support/ipxe-commands/ipxe-commands_local.bb
This PR introduce `systemd` service that will execute on boot `ipxe-command` if exists. It can be used to pass and execute linux commands from ipxe shell.
Service status if `/sbin/ipxe-command` script doesn't exist:
```
* ipxe-commands.service - iPXE commands autostart on boot
Loaded: loaded (8;;file://DasharoToolsSuite/lib/systemd/system/ipxe-commands.service/lib/systemd/system/ipxe-commands.service8;;; enabled; vendor8;;>
Active: inactive (dead)
Condition: start condition failed at Mon 2023-01-16 14:08:17 UTC; 23s ago
`- ConditionPathExists=/sbin/ipxe-commands was not met
```
---
You will need to create script file with `dts.ipxe` boot menu in folder with DTS binaries (in default configuration it should be ` build/tmp/deploy/images/genericx86-64`). Example content of `dts.ipxe` menu: …
> Autoboot script passed by iPXE shell

- CHANGELOG.md
- meta-dts-distro/conf/distro/dts-distro.conf
- meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
Fixes updating from v1.5.0 to v1.5.1 and v1.7.0 to v1.7.1
> dts/dts-functions.sh: fix updating boards without Vboot slot B

- scripts/generate-ipxe-menu.sh
The imgverify will probably will not be added in this iteration. We will still need to create our signing certificate and also create script in such a way that it handles correctly devices whete such command is not present.
Tested on: https://boot.dasharo.com/dts/dtss.ipxe
> scripts/generate-ipxe-menu.sh: more readable script, prepare for imgverify

- .github/workflows/ci.yml
- .github/workflows/develop.yml
- .github/workflows/weekly.yml
Sometimes we run into random errors while building DTS image (e.g. unable to fetch repository from github etc.). Thanks to this we will try maximum 5 times to build an image before giving up.
> workflows: rerun build step in case of error

- meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy
- meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
Make the console output for settings and logo migration a bit more understandable to users, and pipe all cbfstool messages including stderr to error logs
> dasharo-deploy: update smmstore and bootsplash migration console output

- scripts/commands.sh
- scripts/local-ipxe-server.sh
This is a script that automatically takes the dts version from `dts-distro.conf`, then downloads that version, and makes a `dts.ipxe` script that boots using the downloaded `bzImage` and `.cpio.gz`, and finally starts a server to allow connected computers to boot from the iPXE shell using the created `dts.ipxe`
> scripts/ipxe-dts.sh: added

- meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
Fix for issue https://github.com/Dasharo/dasharo-issues/issues/699. Verified *only on* `NV41MZ`.
Before the changes:
```shell
Waiting for network connection ...
Checking if board is Dasharo compatible.
Gathering flash chip and chipset information...
Flash information: vendor="Programmer" name="Opaque flash chip"
Flash size: 16M
Getting platform specific GPG key... Done
Backing up BIOS firmware and store it locally...
Remember that firmware is also backed up in HCL report.
Checking for Open Source Embedded Controller firmware
Backing up EC firmware...
Failed to read EC firmware backup : (1)
```
After the changes:
```shell
Waiting for network connection ...
Checking if board is Dasharo compatible.
Gathering flash chip and chipset information...
Flash information: vendor="Programmer" …
```
> Add flags for NovaCustom EC flashing

- meta-dts-distro/wic/usb-stick-dts.wks.in
To be able to use both BIOS and UEFI BIOS the boot partition should be a part of MBR partition table and have EFI type. Solution for https://github.com/Dasharo/dasharo-issues/issues/692.
**Logs for verification**:
Before the changes (using `fdisk`):
```bash
Disk /dev/sdc: 14.46 GiB, 15525216256 bytes, 30322688 sectors
Disk model: USB DISK 2.0    
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x32e7839e
Device     Boot Start     End Sectors  Size Id Type
/dev/sdc1  *     2048   78569   76522 37.4M  c W95 FAT32 (LBA)
/dev/sdc2       79872 2177023 2097152    1G 83 Linux
```
After the changes (using `fdisk`):
```bash
Disk /dev/sdc: 14.46 GiB, 15525216256 bytes, …
```
> Change boot partition to efi type

- kas-uefi-sb.yml
- meta-dts-distro/recipes-kernel/kernel/linux-yocto_%.bbappend
This configuration variable is already set to m by meta-secure-core layer and its sublayer.
The issue is documented in https://github.com/Dasharo/dasharo-issues/issues/729.
> Fix setting EFI_VARS config for build with UEFI SB enabled

- meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
A fix for https://github.com/Dasharo/dasharo-issues/issues/752. The core of the problem revolved around the use of the ping command for network connectivity verification, which relied on ICMP packets. This approach posed limitations in environments where ICMP packets are blocked or filtered, leading to false negatives in connectivity checks. The implementation replaces `ping` with  `wget --spider` that is used to check for cloud.3mdeb.com access without downloading content.  By using `wget`, the script now supports environments where ICMP is not an option
> dts: dts-functions: make dts not use ICMP for network connection check

- .github/workflows/ci.yml
- .github/workflows/develop.yml
Develop workflow doesn't deploy to GitHub Releases page.
> workflow: Change action and jobs names

- .github/workflows/ci.yml
- .github/workflows/develop.yml
Test will fail if conflicting versions are present in the push tag and `meta-dts/meta-dts-distro/conf/distro/dts-distro.conf`.
Needs testing before merging
> workflows: get DTS_VER from tag not dts-distro.conf

- meta-dts-distro/recipes-devtool/python/python3-pgpdump_1.5.bb
- meta-dts-distro/recipes-devtool/python/python3-roca-detect_git.bb
Do we need this tool? Is it even maintained? Has it ever worked (if not then clearly we don't need it as someone would have noticed it's broken)
From what I can see last commit was 4 years ago, last comment by maintainer (PR/issue) probably closer to 6. 
roca-detect requires `python3-cryptography`:
```
bash-5.2# ssh-keygen
(...)
bash-5.2# roca-detect .ssh/
Traceback (most recent call last):
File "/usr/bin/roca-detect", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib/python3.12/site-packages/roca/detect.py", line 2253, in main
app.main()
File "/usr/lib/python3.12/site-packages/roca/detect.py", line 2248, in main
self.work()
File "/usr/lib/python3.12/site-packages/roca/detect.py", line 2143, in work
ret = self.process_inputs()
^^^^^^^^^^^^^^^^^^^^^
File …
```
> python3-roca-detect: fix missing dependencies

- kas-uefi-sb.yml
- meta-dts-distro/conf/distro/dts-sb-distro.conf
Before changes:
```
`ERROR: Layer networking-layer is not compatible with the core layer which only supports these series: scarthgap (layer is compatible with kirkstone)`
```
Using the same refspec as `common.yml`:
```diff
meta-openembedded:
-    url: https://git.openembedded.org/meta-openembedded
-    refspec: 0b78362654262145415df8211052442823b9ec9b
layers:
-      meta-oe:
-      meta-networking:
-      meta-python:
meta-perl:
```
Results in:
```
ERROR: Layer secure-core is not compatible with the core layer which only supports these series: scarthgap (layer is compatible with kirkstone honister langdale)
```
After updating `meta-secure-core`
```diff
meta-secure-core:
url: https://github.com/Wind-River/meta-secure-core
-    refspec: fa438247c3e61d7f746687d85ef3b0dd66dc6b3f
+    refspec: …
```
> DTS fix UEFI SB build

- meta-dts-distro/recipes-extended/sbctl/sbctl_0.15.4.bb
Dependencies taken from GitHub repository README: needed dependencies are `objcopy` from binutils and `lsblk` from `util-linux`
> recipes-extended: sbctl: add RDEPENDS to recipe

- kas/cache.yml
PR removes warning:
```
WARNING: You are using a local hash equivalence server but have configured an sstate mirror.
This will likely mean no sstate will match from the mirror. You may wish to disable the hash equivalence
use (BB_HASHSERVE), or use a hash equivalence server alongside the sstate mirror.
```
Built from scratch:
```
Sstate summary: Wanted 4441 Local 0 Mirrors 4434 Missed 7 Current 0 (99% match, 0% complete)
NOTE: Executing Tasks
(...)
NOTE: Tasks Summary: Attempted 8865 tasks of which 8839 didn't need to be rerun and all succeeded.
```
Built on different machine with local cache
```
Sstate summary: Wanted 1123 Local 9 Mirrors 1107 Missed 7 Current 3318 (99% match, 99% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 8865 tasks of which 8843 didn't need to be …
```
> kas: cache.yml: don't use local hash equivalence server

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Related PR: https://github.com/Dasharo/dts-scripts/pull/58.
> distro: dts-scripts: fix check_for_dasharo_firmware

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
@DaniilKl started osfv test by setting target branch to main for a second. Let's wait for results as my PR made few changes.
> Dts scripts enhanced logging

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
DPP Packages are now called DTS Extensions to prevent confusion.
Related PR: https://github.com/Dasharo/dts-scripts/pull/62
> Fix DTS Extensions messages

- .github/workflows/test.yml
Without it grep buffers a lot of lines before output is logged to console and shown in GitHub Actions, usually after every test finishes.
> workflow: test.yml: use line buffering with grep

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
HCL report collects information, if smth is missing or not working - it still should be collected by HCL report. Therefore, there should be no exit on error inside HCL report.
> distro: dts-scripts: HCL should not exit on error

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Don't merge before: https://github.com/Dasharo/dts-scripts/pull/73
> dts-scripts: fix ODROID-H4 firmware link and initial deployment

- .github/workflows/test.yml
The change was caused by https://github.com/Dasharo/open-source-firmware-validation/pull/952
> Use Python 3.13 for DTS testing workflow

- .github/workflows/test.yml
Used e.g. to verify which tests use profile:
```text
[ WARN ] Workflow isn't configured for profile verification.
E2E037: msi-pro-z690-a-ddr5 UEFI Update - DCR                         | PASS |
```
> workflow: show '[ WARN ]' lines when running tests

- CHANGELOG.md
- meta-dts-distro/conf/distro/dts-distro.conf
- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
1st run: couple failures, forgot to merge https://github.com/Dasharo/open-source-firmware-validation/pull/1115.
There is also issue with ODROID ultra, someone copied DTS E2E variables from H4+: https://github.com/Dasharo/open-source-firmware-validation/blob/a1694c87c74fda23fb01de0e97e735ced5e83b6a/platform-configs/odroid-h4-ultra.robot#L140
---
Failed tests:
```
E2E007.002 Check old credentials are being overwritten by new :: M... | FAIL |
E2E007.003 Check wrong credentials should not allow to log into DP... | FAIL |
E2E007.005 Check empty e-mail should not pass :: Entering empty e-... | FAIL |
E2E007.006 Check empty password should not pass :: Entering empty ... | FAIL |
E2E007.009 Check DPP credentials with access to only extensions ::... | FAIL |
E2E008: novacustom-v540tnd Fuse …
```
> Release v2.7.1

- meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Also migrate most user confirmation to single function to simplify testing and remove code duplication. This results in those questions not accepting default value (most of those didn't accept any default anyway), and unifying possible choice to always display '[y|n]' with no variation (e.g. '(y/n)')
> dts-scripts: add mocking to allow fum, smmstore, and flash testing
