meta-dts-distro/recipes-dts/dts/files/dts, meta-dts-distro/recipes-dts/reports/dasharo-hcl-report/dasharo-hcl-report
- Resolves Dasharo/dasharo-issues#92
=> MAC removed from logs uploaded to Dasharo cloud

meta-dts-distro/conf/distro/dts-distro.conf, meta-dts-distro/recipes-bsp/packagegroups/packagegroup-coreboot-utils.bb, meta-dts-distro/recipes-dts/dts/dts/dts, meta-dts-distro/recipes-dts/packagegroups/packagegroup-dts.bb, meta-dts-distro/recipes-dts/reports/dasharo-hcl-report/dasharo-hcl-report
Add important fixes after hcl improvements
=> Hcl report fixes

meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy
Initial deployment on Dell Precision T1650 was tested successfully on this branch
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
=> distro: dasharo-deploy: fix path for SCH5545_FW used with T1650 model

README.md
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>
=> README.md: make commands copypastable

meta-dts-distro/conf/distro/dts-distro.conf, meta-dts-distro/recipes-core/initrdscripts/initramfs-framework/setup-live, meta-dts-distro/recipes-core/initrdscripts/initramfs-module-setup-live_1.0.bbappend
Fixes https://github.com/Dasharo/dasharo-issues/issues/288
ISO not tested,  nor built through CI.
=> dts-distro.conf: add support for iso building

meta-dts-distro/conf/distro/dts-distro.conf, meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy, meta-dts-distro/recipes-dts/dts/dts/dts, meta-dts-distro/recipes-dts/dts/dts/dts-environment.sh, meta-dts-distro/recipes-dts/reports/dasharo-hcl-report/dasharo-hcl-report
… MSI
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
=> dts: dasharo-deploy: use baseboard name for MSI

meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy, meta-dts-distro/recipes-dts/dts/dts/cloud_list, meta-dts-distro/recipes-dts/dts/dts/dts, meta-dts-distro/recipes-dts/dts/dts/dts-environment.sh, meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
curl needs -L flag to correctly use link redirection
=> Bugfix: links redirect

meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy, meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
Checked on the NovaCustom NS5X TGL
Also checked on Dell Optiplex 7010 and Protectli VP4630 that the path /sys/class/power_supply/AC does not exist there.
=> dts: add check_if_ac() before fw update

meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy, meta-dts-distro/recipes-dts/dts/dts/dts, meta-dts-distro/recipes-dts/dts/dts/ec_transition, meta-dts-distro/recipes-dts/packagegroups/packagegroup-dts.bb, meta-dts-distro/recipes-support/system76-ectool/system76-ectool_0.3.8.bb
For convenience, print IP addresses when enabling SSH, so we don't have to drop to shell to check manually every time
=> Dasharo ectool

.github/workflows/ci.yml, .github/workflows/develop.yml
Closes https://github.com/Dasharo/meta-dts/issues/70
After merging also https://git.3mdeb.com/3mdeb/dts-release-cicd-pipeline/pulls/4 needs to be merged.
=> Include wic.bmap files in prod and dev releases

.github/workflows/ci.yml, .github/workflows/develop.yml, README.md, meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh, scripts/get_last_commit.sh, scripts/update_components.sh
* Added scripts to automatically update recipes with Dasharo-forked repositories
* Run those on prod CI/CD jobs
=> Auto update dasharo refspec

meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy, meta-dts-distro/recipes-dts/dts/dts/dts-functions.sh
In new Dasharo releases EC update will be done by firmware after first reboot.
=> Remove separate EC update when updating Dasharo

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb, meta-dts-distro/recipes-dts/images/dts-base-image.inc, meta-dts-distro/recipes-extended/minio-cli/minio-cli_git.bb
This PR introduces subscription-based packaging. The goal is to implement system which will pull and install packages after user logging in that will make workflow.
=> Premium packages integration

.github/workflows/ci.yml, .github/workflows/develop.yml
Fixes `Trigger Signing` step e.g.:
https://github.com/Dasharo/meta-dts/actions/runs/11008588081/job/30576446442
Should be tested with new release
Related: https://github.com/Dasharo/dasharo-issues/issues/1052
=> workflows: fix dts-release-cicd-pipeline ssh errors

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Should not be merged before https://github.com/Dasharo/dts-scripts/pull/31
=> dts-scripts: update to version with ODROID-H4+ support

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Don't merge before https://github.com/Dasharo/dts-scripts/pull/33
=> distro: dts-scripts: add support for NovaCustom V5x0TNx

.github/workflows/ci.yml, .github/workflows/develop.yml
=> workflows: get DTS_VER from tag not dts-distro.conf

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Adds https://github.com/Dasharo/dts-scripts/pull/43
=> dts-scripts: update srcrev: add vbt to hcl report

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Don't merge before https://github.com/Dasharo/dts-scripts/pull/54.
Should be tested on both NS5xMU & NS7xMU.
=> Fix boardmismatch unhandled parameter error on NS50MU TGL

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Don't merge before https://github.com/Dasharo/dts-scripts/pull/56
=> dts-scripts: fix acpidump command in HCL report

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Related PRs:
https://github.com/Dasharo/open-source-firmware-validation/pull/640
https://github.com/Dasharo/dts-scripts/pull/57
=> Change DTS Extensions message

README.md
Cherrypick from https://github.com/Dasharo/meta-dts/pull/201
=> README.md: update old information

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Related to https://github.com/Dasharo/dts-scripts/pull/87
=> distro: dts-scripts: add SeaBIOS support

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
- profile generation - generate /tmp/logs/profile and debug_profile with list of called HAL commands, arguments and return values. debug_profile also contains script and line of called command along with function which called this command.
- HCL report - add missing LSPCI and LSUSB HAL variables
- password indent - fix DPP password indent so it's the same as in e-mail
=> dts-scripts: add profile generation, fix HCL report & password indent

.github/workflows/test.yml, meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Fixes this issue: https://github.com/Dasharo/dasharo-issues/issues/1382
=> Fix test CI

meta-dts-distro/recipes-dts/dts-scripts/dts-scripts_git.bb
Odroid H4 Initial deployment and Transition
=> distro: dts-scripts: add Dasharo (Slim Bootloader+UEFI) for Hardkernel

kas/common.yml, meta-dts-distro/recipes-dts/packagegroups/packagegroup-dts.bb
=> meta-dts-distro: Add PSPTool
